sonar.projectKey=java-sonar-runner-petclinic-2
sonar.projectName=java-sonar-runner-petclinic-2 analyzed with the SonarQube Runner 
sonar.projectVersion=1.0
sonar.sources=src 
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
